# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 197fb713c32cd371824ad75c247cae095766344f9e87da8c5916614f7c3ca1330160a140d13416e5bd6ec39f94c36c95da2661f4fae0c689ca294f805202ccfd

test:
  secret_key_base: 27ec795ef688a719d6dd540f4a5c37628180719667c40a9419d0894f9fac4d1b1035e83cd09d59b6b13e449c4ddd97a7e8d9cdda427fdb36d0216ce8e52a8a78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
